"""Add tables

Revision ID: 50ab11aec078
Revises: e1d0907b3163
Create Date: 2026-08-24 10:06:11.963776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50ab11aec078'
down_revision: Union[str, Sequence[str], None] = 'e1d0907b3163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_permissions',
    sa.Column('role_id', postgresql.UUID(), nullable=False),
    sa.Column('permission_id', postgresql.UUID(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['identity.permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['identity.roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions')),
    schema='identity'
    )
    op.create_index('ix_role_permissions_permission_id', 'role_permissions', ['permission_id'], unique=False, schema='identity')
    op.create_index('ix_role_permissions_role_id', 'role_permissions', ['role_id'], unique=False, schema='identity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_role_permissions_role_id', table_name='role_permissions', schema='identity')
    op.drop_index('ix_role_permissions_permission_id', table_name='role_permissions', schema='identity')
    op.drop_table('role_permissions', schema='identity')
    # ### end Alembic commands ###
