"""change user-role's expire_at to nullable

Revision ID: 8134bd257777
Revises: 50ab11aec078
Create Date: 2026-08-25 01:58:44.664563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8134bd257777'
down_revision: Union[str, Sequence[str], None] = '50ab11aec078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_roles', 'expired_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               schema='identity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_roles', 'expired_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               schema='identity')
    # ### end Alembic commands ###
