"""Init database

Revision ID: e1d0907b3163
Revises: 
Create Date: 2026-08-22 02:30:13.118735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1d0907b3163'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("code::text ~ '^[a-z][a-z0-9)_.:-]*$'", name=op.f('ck_permissions_code')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name=op.f('uq_permissions_code')),
    schema='identity'
    )
    op.create_table('roles',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.TEXT(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_system', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("code::text ~ '^[a-z][a-z0-9)_]*$'", name=op.f('ck_roles_code')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code')),
    schema='identity'
    )
    op.create_table('users',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('username', sa.TEXT(), nullable=False),
    sa.Column('email', sa.TEXT(), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auth_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'active', 'locked', 'disabled')", name=op.f('ck_users_status')),
    sa.CheckConstraint('auth_version > 0', name=op.f('ck_users_auth_version')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username')),
    schema='identity'
    )
    op.create_table('action_tokens',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', postgresql.UUID(), nullable=False),
    sa.Column('purpose', sa.String(length=24), nullable=False),
    sa.Column('token_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_ip', postgresql.INET(), nullable=True),
    sa.CheckConstraint("purpose IN ('verify_email', 'reset_password')", name=op.f('ck_action_tokens_ck_action_tokens_purpose')),
    sa.CheckConstraint('consumed_at IS NULL OR consumed_at >= created_at', name=op.f('ck_action_tokens_ck_action_tokens_consumed')),
    sa.CheckConstraint('expires_at > created_at', name=op.f('ck_action_tokens_ck_action_tokens_expiry')),
    sa.CheckConstraint('octet_length(token_hash) = 32', name=op.f('ck_action_tokens_ck_action_token_hash_size')),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], name=op.f('fk_action_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_tokens')),
    sa.UniqueConstraint('token_hash', name='uq_action_tokens_hash'),
    schema='identity'
    )
    op.create_table('password_credentials',
    sa.Column('user_id', postgresql.UUID(), nullable=False),
    sa.Column('password_hash', sa.TEXT(), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('must_change_password', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False),
    sa.Column('failed_attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('failed_attempt_count >= 0', name=op.f('ck_password_credentials_failed_attempts')),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], name=op.f('fk_password_credentials_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_password_credentials')),
    schema='identity'
    )
    op.create_table('sessions',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', postgresql.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.String(length=50), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.TEXT(), nullable=True),
    sa.CheckConstraint('expires_at > created_at', name=op.f('ck_sessions_expiry')),
    sa.CheckConstraint('revoked_at IS NULL OR revoked_at >= created_at', name=op.f('ck_sessions_revoked')),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    schema='identity'
    )
    op.create_index('ix_sessions_user_state', 'sessions', ['user_id', 'revoked_at', 'expires_at'], unique=False, schema='identity')
    op.create_table('user_roles',
    sa.Column('user_id', postgresql.UUID(), nullable=False),
    sa.Column('role_id', postgresql.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assigned_by', postgresql.UUID(), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('expired_at IS NULL OR expired_at > assigned_at', name=op.f('ck_user_roles_expiry')),
    sa.ForeignKeyConstraint(['assigned_by'], ['identity.users.id'], name=op.f('fk_user_roles_assigned_by_users')),
    sa.ForeignKeyConstraint(['role_id'], ['identity.roles.id'], name=op.f('fk_user_roles_role_id_roles')),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], name=op.f('fk_user_roles_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles')),
    schema='identity'
    )
    op.create_index('idx_user_roles_role_id', 'user_roles', ['role_id'], unique=False, schema='identity')
    op.create_index('idx_user_roles_user_expiry', 'user_roles', ['user_id', 'expired_at'], unique=False, schema='identity')
    op.create_table('auth_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', postgresql.UUID(), nullable=True),
    sa.Column('session_id', postgresql.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('success', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.TEXT(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['identity.sessions.id'], name=op.f('fk_auth_events_session_id_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], name=op.f('fk_auth_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_events')),
    schema='identity'
    )
    op.create_table('refresh_tokens',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', postgresql.UUID(), nullable=False),
    sa.Column('token_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('parent_token_id', postgresql.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('expires_at > created_at', name=op.f('ck_refresh_tokens_expiry')),
    sa.CheckConstraint('octet_length(token_hash) = 32', name=op.f('ck_refresh_tokens_hash_size')),
    sa.CheckConstraint('revoked_at IS NULL OR revoked_at >= created_at', name=op.f('ck_refresh_tokens_revoked')),
    sa.CheckConstraint('used_at IS NULL OR used_at >= created_at', name=op.f('ck_refresh_tokens_used')),
    sa.ForeignKeyConstraint(['parent_token_id'], ['identity.refresh_tokens.id'], name=op.f('fk_refresh_tokens_parent_token_id_refresh_tokens'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['identity.sessions.id'], name=op.f('fk_refresh_tokens_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash')),
    schema='identity'
    )
    op.create_index('ix_refresh_tokens_parent', 'refresh_tokens', ['parent_token_id'], unique=False, schema='identity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_refresh_tokens_parent', table_name='refresh_tokens', schema='identity')
    op.drop_table('refresh_tokens', schema='identity')
    op.drop_table('auth_events', schema='identity')
    op.drop_index('idx_user_roles_user_expiry', table_name='user_roles', schema='identity')
    op.drop_index('idx_user_roles_role_id', table_name='user_roles', schema='identity')
    op.drop_table('user_roles', schema='identity')
    op.drop_index('ix_sessions_user_state', table_name='sessions', schema='identity')
    op.drop_table('sessions', schema='identity')
    op.drop_table('password_credentials', schema='identity')
    op.drop_table('action_tokens', schema='identity')
    op.drop_table('users', schema='identity')
    op.drop_table('roles', schema='identity')
    op.drop_table('permissions', schema='identity')
    # ### end Alembic commands ###
